server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        service-name: gateway
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        deregister-critical-service-after: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

management.tracing:
  sampling.probability: 1
  exporter.zipkin.endpoint: http://localhost:9411/api/v2/spans
