server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        serviceName: ${spring.application.name}
        preferIpAddress: true
        instanceId: ${spring.application.name}-${SERVER_PORT:${server.port:8080}}
        healthCheckUrl: http://host.docker.internal:${SERVER_PORT:${server.port:8080}}/actuator/health
        healthCheckInterval: 10s
        deregisterCriticalServiceAfter: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

management.tracing:
  sampling.probability: 1
  exporter.zipkin.endpoint: http://localhost:9411/api/v2/spans
