server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${SERVER_PORT:${server.port:8080}}
        health-check-url: http://host.docker.internal:${SERVER_PORT:${server.port:8080}}/actuator/health
        health-check-interval: 10s
        deregister-critical-service-after: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
    exporter:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
