server:
  port: ${SERVER_PORT:8900}

spring:
  application:
    name: stock-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        serviceName: ${spring.application.name}
        preferIpAddress: true
        instanceId: ${spring.application.name}-${SERVER_PORT:${server.port:8900}}
        healthCheckUrl: http://host.docker.internal:${SERVER_PORT:${server.port:8900}}/actuator/health
        healthCheckInterval: 10s
        deregisterCriticalServiceAfter: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
  endpoint:
    health:
      probes:
        enabled: true

management.tracing:
  sampling.probability: 1.0
  exporter.zipkin.endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

