server:
  port: ${SERVER_PORT:8902}

spring:
  application:
    name: stock-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8501}
      discovery:
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${server.port}
        health-check-url: http://host.docker.internal:${server.port}/actuator/health
        health-check-interval: 10s
        deregister-critical-service-after: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
  endpoint:
    health:
      probes:
        enabled: true

management.tracing:
  sampling.probability: 1.0
  exporter.zipkin.endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

